jobs:
  pyinstaller-build:
    runs-on: <windows-latest / ubuntu-latest / mac-latest>
    steps:
      - name: PyInstaller Action
  uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.6'
          spec: 'src/build.spec'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'My executable'
          options: --onefile, --name "My App", --windowed, 
